name: NBS
dependencies:
  - python=3
  - conda-forge::gdal=2.4
  - numpy
  - scipy
  - matplotlib
  - fiona
  - rasterio
  - astropy
  - pytables
  - conda-forge::pykrige
  - psycopg2
  - lxml
  - requests
  - spyder
  - wxpython