name: NBS
channels:
  - conda-forge
dependencies:
  - python=3
  - conda-forge::gdal=2.4.2
  - numpy
  - scipy
  - matplotlib
  - fiona
  - mongoengine
  - astropy
  - pytables
  - pykrige
  - lxml
  - requests
  - spyder
  - wxpython